# Generated by Django 5.0.6 on 2024-06-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('how_learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagearticle',
            name='date',
        ),
    ]
