# Generated by Django 5.0.6 on 2024-06-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('how_learn', '0003_modelcontent_delete_imagearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontent',
            name='phone',
            field=models.CharField(default='00000000', max_length=23),
        ),
        migrations.AddField(
            model_name='modelcontent',
            name='zip_code',
            field=models.CharField(default='252552', max_length=34),
        ),
    ]
