# Generated by Django 5.0.6 on 2024-06-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('how_learn', '0004_modelcontent_phone_modelcontent_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='modelcontent',
            name='phone',
            field=models.CharField(max_length=23),
        ),
        migrations.AlterField(
            model_name='modelcontent',
            name='zip_code',
            field=models.CharField(max_length=34),
        ),
    ]
