# Generated by Django 5.0.6 on 2024-06-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('how_learn', '0005_modelcontent_image_alter_modelcontent_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcontent',
            old_name='image',
            new_name='image_field',
        ),
    ]
